### PR TITLE
WCOR-1125: Image embed styles, full and half width.

### PR DESCRIPTION
**Pull request by jmilden-git**
### ODE 100

**Use Case** 

As an editor I would like to choose either half or full width image layout for my page.  The system will display my image resized to fit my chosen layout.

**Implementation Details**

Modify media settings to allow choice between full 100% width or half 50% width display of an image.  Create image styles (2) and display modes (2) to use the correct styles.

Enable Responsive Image module.

4 new image styles (documented in Spec Tool)

Max 325x325

Max 650x650

Max 1300x1300

Max 2600x2600

**Dependencies**

Need test page
Need test image

**Test Plan**

Upload an image to media library for use.  In test page, use the media embed button to embed the image, set the display to full width.  Preview the page and ensure the image is full width and responds to viewport size changes (responsive).  Upload an image and choose the 50% width display option, view the page and ensure the image displays at 50% at desktop width, and 100% width for mobile width.

### CODE REVIEW

**Comment by sharstine** [comment]
I'll do the QA on this.

**Comment by sharstine** [comment]
@jmilden-git - I'm unable to upload an image to the media library. Below are the methods I tried.

**Method 1:**
1. Go to /media/add/image.
2. Enter a name.
3. Select an image.
4. Click "Save."

When I click Save, I get an error saying that the Image field is required, even though I selected an image.

**Method 2:**
1. Create a new page.
2. In the Body field, click the "Insert from Media Library" icon in the RTE.
3. On the Image tab, select a file.
4. Click "Insert selected."

Nothing happens when I click "Insert selected."

**Comment by jmilden-git** [comment]
> @jmilden-git - I'm unable to upload an image to the media library. Below are the methods I tried.
> 
> **Method 1:**
> 
> 1. Go to /media/add/image.
> 2. Enter a name.
> 3. Select an image.
> 4. Click "Save."
> 
> When I click Save, I get an error saying that the Image field is required, even though I selected an image.
> 
> **Method 2:**
> 
> 1. Create a new page.
> 2. In the Body field, click the "Insert from Media Library" icon in the RTE.
> 3. On the Image tab, select a file.
> 4. Click "Insert selected."
> 
> Nothing happens when I click "Insert selected."

Scott, there is apparently a bug with the lack of integration between the AWS file storage and our ODEs.  This will need to be addressed next week before this PR can be finalized.

**Comment by lgbridges** [comment]
> Scott, there is apparently a bug with the lack of integration between the AWS file storage and our ODEs. This will need to be addressed next week before this PR can be finalized.

@sharstine @jmilden-git -- The AWS secrets/credentials are not automatically populated into the ODEs at creation time.

Before QA begins, you will need to run ``` blt custom:secret [ode-number] ``` to import the secrets to that ODE environment.

Having done that for this story, I was able to successfully save the image.

**Review by lgbridges — APPROVED** [review]
CR / QA passes.

I'm noting that the responsive functionality is roughly working according to test plan, but the dimensions of the test image are a bit variable. In particular, the image appearance on iPad/tablet deviates from expected size. Test plan passes based on stated criteria, but a follow-up story may be required to investigate and/or refine breakpoints or resize rules.

Original 905x524

FULL-WIDTH
Desktop 640x370
Galaxy S5 325x188
iPad 623x360

HALF-WIDTH
Desktop 420x243
Galaxy S5 325x188
iPad 207x120

**Comment by sharstine** [comment]
@lgbridges, @jmilden-git - There may have been a miscommunication about QA on this story. I had started doing QA last week until I reached a blocker when uploading images. I was continuing QA this morning after Lee ran the command ``` blt custom:secret 100 ```. My test results are a bit different than Lee's. ODE 100 is no longer available so my notes are incomplete, but here's what I initially drafted:

**Images I uploaded:**
https://washcoda.s3.us-west-2.amazonaws.com/wcor/2021-07/hot-air-balloon.jpg (576 x 324)
https://washcoda.s3.us-west-2.amazonaws.com/wcor/2021-07/tree.png (1024 x 768)
https://washcoda.s3.us-west-2.amazonaws.com/wcor/2021-07/DigitalGlobe_WorldView1_50cm_8bit_BW_DRA_Bangkok_Thailand_2009JAN06_8bits_sub_r_1.jpg (4386 x 4368)

**Test page I created:**
https://wcorode100.prod.acquia-sites.com/administration/scotts-test-page

**Blockers:**
1. Most of the full width images on my test page do not appear to consume the full the width of the page in desktop and iPad viewports. The full width images seem to fall back to 480px. According to the responsive image style settings, the fallback image style only appears on the site if an error occurs.

2. Full width "left aligned" images are smaller than full width "center aligned" images on desktop.

3. Half width images are visually much smaller than half the width of the page on desktop (going based on memory).

**Non-blockers (possible ideas for future stories):**
- On /media/add/image, the "On" checkbox could use a better label. Maybe "Shared" instead?
- When I click the Add Media icon in the RTE and choose a file on the Image tab, and then switch over to the Document or Video/Audio tab, and go back to the Image tab, the image I selected is gone.
- When I click the Add Media icon in the RTE, the "Add or select media" modal is pushed to the right of the screen and I don't see a way to drag it to the center. I'm using Chrome.
- Images inserted through the Add Media icon in the RTE are centered by default. Why not left aligned?
- After I insert a media item, I can't insert any content under it unless I add extra spacing before inserting the image.

**Pull request merged**
