### PR TITLE
WCOR-1179: Add migration status field.

### PR DESCRIPTION
**Pull request by lgbridges**
## ODE 161

**Use case**

As a site admin, I need to see the readiness of any given page or group to be published and for which content migration should be considered "complete".

As an editor or other internal stakeholder, I would like to view the migration status of any given page.

**Implementation details**

Create a Migration Status field and implement for Page and Group content. Uses a Migration Status taxonomy to include values "In migration", "Review", and "Accepted".

**Test plan**

- [x] As a site admin, I can set a value for Migration Status field on a Page or Group item.
- [x] As Eddie Editor, I can view the value set for Migration Status on that Page or Group item.

### CODE REVIEW

**Comment by sharstine** [comment]
I'll begin QA on this tomorrow (Wednesday) morning.

**Comment by sharstine** [comment]
@lgbridges - The "Migration status" taxonomy exists on ODE 161, but contains no terms. I believe this is the expected behavior as terms are considered content, not configuration. For testing purposes, I can add add the terms "In migration," "Review," and "Accepted" on ODE 161. Are there any additional steps you/we need to take to ensure these terms are added to Dev?

**Comment by lgbridges** [comment]
> 
> 
> @lgbridges - The "Migration status" taxonomy exists on ODE 161, but contains no terms. I believe this is the expected behavior as terms are considered content, not configuration. For testing purposes, I can add the terms "In migration," "Review," and "Accepted" on ODE 161. Are there any additional steps you/we need to take to ensure these terms are added to Dev?

Thanks, forgot to add the taxonomy to Dev in advance. It's there now. If you're OK with adding the taxonomy and terms to the ODE, that will allow the test plan to work. Otherwise I can re-run Pipelines. Let me know, thanks.

**Comment by sharstine** [comment]
> > @lgbridges - The "Migration status" taxonomy exists on ODE 161, but contains no terms. I believe this is the expected behavior as terms are considered content, not configuration. For testing purposes, I can add the terms "In migration," "Review," and "Accepted" on ODE 161. Are there any additional steps you/we need to take to ensure these terms are added to Dev?
> 
> @sharstine -- Thanks, forgot to add the taxonomy to Dev in advance. It's there now. If you're OK with adding the taxonomy and terms to the ODE, that will allow the test plan to work. Otherwise I can re-run Pipelines. Let me know, thanks.

No worries. I've added the taxonomy terms to the ODE. Just wanted to make sure I understood the process. I'll add final QA notes here after I finish reviewing.

**Comment by sharstine** [comment]
@lgbridges - QA passes. As a future enhancement, it might be useful to have a migration dashboard (or simply a filter on the "Content" and "My content" pages) to see migration status at a higher level than just one page.

Not sure who does code review on this -- @gatoona or @jmilden-git?

**Comment by gatoona** [comment]
@lgbridges getting an error in builds:

> The import failed due to the following reasons:                                                                                                        
    Entities exist of type <em class="placeholder">Taxonomy term</em> and <em c                                                                            
    lass="placeholder">Vocabulary</em> <em class="placeholder">Migration status                                                                            
    </em>. These entities need to be deleted before importing.     

Likely reason is that changes were made to the dev environment directly prior to merging this PR.

**Comment by lgbridges** [comment]
> 
> 
> @lgbridges getting an error in builds:
> 
> > The import failed due to the following reasons:
> > Entities exist of type _Taxonomy term_ and _Vocabulary_ _Migration status
> > _. These entities need to be deleted before importing.
> 
> Likely reason is that changes were made to the dev environment directly prior to merging this PR.

Created the taxonomy on dev in error. Deleted the taxonomy on dev site now, hopefully this corrects the issue.

**Review by gatoona — APPROVED** [review]

**Pull request merged**
