### PR TITLE
WCOR-1159: Implement breadcrumb navigation.

### PR DESCRIPTION
**Pull request by lgbridges**
### Use case

As a site visitor (anon), I can see breadcrumb navigation that provides a link back to (A) the menu parent item of the current item and (B) the "Displayed in" group for the current item.

### Implementation details

- Implement Easy Breadcrumb / Menu Breadcrumb
- Determine menu population scheme to make Menu Breadcrumb active

### Test plan

As site admin --

- [x] Create a page called "Test Parent" and populate a Group into "Displayed in" field.
- [x] Create a page called "Test Child." Check "Show in menu", and in the Menu parent field, choose "Test Parent." Choose the same "Displayed in" group as you did for "Test Parent."
- [x] View the "Test Child" page and note that the breadcrumb nav trail reads "Home > [Displayed in group] > Test Parent".

### CODE REVIEW

**Comment by sharstine** [comment]
@lgbridges - I completed the first two items in the test plan (as Eddie Editor). When I go to /ems/test-parent/test-child as an anonymous or authenticated user, I see "Test Parent" in the right sidebar of the page, but not in the breadcrumb trail.

test-parent

**Comment by lgbridges** [comment]
> 
> 
> @lgbridges - I completed the first two items in the test plan (as Eddie Editor). When I go to /ems/test-parent/test-child as an anonymous or authenticated user, I see "Test Parent" in the right sidebar of the page, but not in the breadcrumb trail.
> 
> I get the same result after flushing all caches and running cron.

Will review shortly.

**Comment by lgbridges** [comment]
> 
> 
> @lgbridges - I completed the first two items in the test plan (as Eddie Editor). When I go to /ems/test-parent/test-child as an anonymous or authenticated user, I see "Test Parent" in the right sidebar of the page, but not in the breadcrumb trail.
> 
> I get the same result after flushing all caches and running cron.
> 

Adjusted the test plan -- there isn't anything permissions-sensitive about this functionality, so it can all be done as site admin. Since the prior test plan had us creating pages as Eddie Editor, I had just missed the separate step of publishing the pages (which won't be an issue doing this as site admin). 

Ready for QA.

**Comment by sharstine** [comment]
Test plan passes. QA complete.

Note: I tried to create an additional level in the breadcrumb trail by adding a test "grandchild" page whose parent is Test Child. In the "Menu parent" field, Test Child is not a page to select from. I assume this is due to some restriction in the number of allowed levels in the breadcrumb.

**Comment by lgbridges** [comment]
> 
> 
> Test plan passes. QA complete.
> 
> Note: I tried to create an additional level in the breadcrumb trail by adding a test "grandchild" page whose parent is Test Child. In the "Menu parent" field, Test Child is not a page to select from. I assume this is due to some restriction in the number of allowed levels in the breadcrumb.

Thanks @sharstine for completing QA -- I'll delete this ODE to make way for the hotfix to create its needed ODE to merge, that should get us moving with the merge on this one. Glad it's Friday!

**Comment by lgbridges** [comment]
> 
> 
> Test plan passes. QA complete.
> 
> Note: I tried to create an additional level in the breadcrumb trail by adding a test "grandchild" page whose parent is Test Child. In the "Menu parent" field, Test Child is not a page to select from. I assume this is due to some restriction in the number of allowed levels in the breadcrumb.

Thanks for the feedback -- it sounds like we may need another story to expand the breadcrumb trail if we do receive requests from authors for a 3-step hierarchy. Until then, I'll just merge this one. ;)

**Review by gatoona — APPROVED** [review]
CR Passes

**Pull request merged**
