### PR TITLE
WCOR-1087: Add Building and Service Location content types and associated view block.

### PR DESCRIPTION
**Pull request by lgbridges**
### ODE68

**Use case**

As a County resident, I want to view information about buildings and service locations. I want to see all service locations for a given building item, and conversely, see the parent building for a given service location.

**Implementation details**

- Create both content type definitions according to spec tool
- Create a view block that will display on building page showing child service locations
- Ensure parent building link displays on service location page

**Test plan**

As an editor, I can add a building item and one or more child service location items.

As a site visitor (anon), I can view a building item and service location item. From a Building item, I can use the right-side region links to jump to the related child service locations.

### CODE REVIEW

**Comment by gatoona** [comment]
@lgbridges not a major issue but it keeps growing, your new PRs seems to include commits made from 27 days ago. Are you working off a clean develop pull in a new branch?

**Comment by lgbridges** [comment]
> 
> 
> @lgbridges not a major issue but it keeps growing, your new PRs seems to include commits made from 27 days ago. Are you working off a clean develop pull in a new branch?

Just noticed that -- I've emptied my IDE before this, but I think these commits are hanging around in my origin / fork, so I will reset that.

**Comment by gatoona** [comment]
Taking QA and CR. Looks like the ODE is not loading Drupal correctly. Possibly due to #88 not being merged in yet.

**Comment by lgbridges** [comment]
> 
> 
> Taking QA and CR. Looks like the ODE is not loading Drupal correctly. Possibly due to #88 not being merged in yet.

I'll take a look.

**Comment by lgbridges** [comment]
#88 merged, ready for QA. CD environment verified functional.

**Comment by gatoona** [comment]
Hey @lgbridges I created a building /node/1251 and a service /node/1256 but not seeing the service listed under the building's page. Also, is it me or is the CDE loading really slow and hanging? Might need to drop that one and rerun pipelines if it's stale. Tried to cache rebuild and cron, but it's still requests still hang.

**Comment by gatoona** [comment]
> Hey @lgbridges I created a building /node/1251 and a service /node/1256 but not seeing the service listed under the building's page. Also, is it me or is the CDE loading really slow and hanging? Might need to drop that one and rerun pipelines if it's stale. Tried to cache rebuild and cron, but it's still requests still hang.

Looks like the nodes were not defaulted to the publish state and needed to be published through the admin content UI. There is no way to control the publish state from inside the node itself unless through scheduler. Can we disable scheduler and enable the publish checkbox in the form display? 

Also regarding the CD environment being slow and failing requests, looks like it's a ongoing Acquia CD issue and not our code base. Having difficulty making requests on a different PR build and even after nuking the old ODE for this PR and generating a new one. Testing the code on the staging environment works fine. Sending Acquia a support ticket in case this issue does not resolve itself soon.

**Review by gatoona — APPROVED** [review]

**Review by gatoona — CHANGES_REQUESTED** [review]
Everything looks good and works as intended. Just need to modify the publish field display and remove scheduler.

**Comment by lgbridges** [comment]
> 
> 
> Everything looks good and works as intended. Just need to modify the publish field display and remove scheduler.

@gatoona -- In keeping with our content workflows implementation (/admin/config/workflow/workflows) that are implemented for the other content types, I added building and service_location to the standard editorial workflow. They were marked for content moderation in the spec tool but I simply forgot to add them to editorial workflow. Now the same moderation state control that appears on the other existing content types should appear on the node edit form for each new type to allow you to directly publish them. This way we also don't have to disable scheduler for these types ("schedulable" was marked Y in spec tool), and I can see use cases for brief service locations that go up and down in a short period of time. Possibly same for buildings.

Let me know if you have any issues with this. Assuming you may want to QA the mod state for these, so marking "needs QA" again.

**Comment by gatoona** [comment]
@lgbridges Publish state looks good. Okay to keep scheduler enabled for those edge cases.
Only issue remaining is that services are shown for buildings they are not listed under.

Service A (/node/1276) added under Public Services (/node/1271) is being shown for that building's page and Justice Court (/node/1281).

**Comment by lgbridges** [comment]
Thanks for the block adjustment, @gatoona -- looks like the services are correctly separated by building now. 

If there's no other QA feedback, I'll go ahead and merge PR.

**Review by gatoona — APPROVED** [review]

**Pull request merged**
