### PR TITLE
WCOR-0020263: Add updated date formats.

### PR DESCRIPTION
**Pull request by jmilden-git**
Ready for Review & QA.  Should be simple for this one.

### CODE REVIEW

**Review by washco-or — DISMISSED** [review]
@jmilden-git Please remove .acquia-cli.yml from this PR and add it to .gitignore.
Please also merge the latest commit #52 (now in develop) into this PR.

-Jung

**Comment by jmilden-git** [comment]
> @jmilden-git Please remove .acquia-cli.yml from this PR and add it to .gitignore.
> Please also merge the latest commit #52 (now in develop) into this PR.
> 
> -Jung

You'll have to show me what you mean.  Not sure why I'd remove the .yml file from the PR.  How do I merge the other PR?

**Comment by gatoona** [comment]
> You'll have to show me what you mean. Not sure why I'd remove the .yml file from the PR.

.acquia-cli.yml is only specific to your local IDE environment. It's your personal configuration.

> How do I merge the other PR?

Run `git pull upstream develop` while checking out feature/STRY0020263 and push.

**Comment by jmilden-git** [comment]
I took the steps Jung indicated.
- added .acquia-cli.yml to gitignore
- git pull upstream develop
- git push -u origin feature/STRY0020263
Let me know if that works.

**Comment by gatoona** [comment]
> I took the steps Jung indicated.
> 
> * added .acquia-cli.yml to gitignore
> * git pull upstream develop
> * git push -u origin feature/STRY0020263
>   Let me know if that works.

@jmilden-git Not seeing your changes anywhere. Please make sure the commit has been successfully pushed.

**Comment by jmilden-git** [comment]
@gatoona My IDE shows the push was successful.  What should I try next?

**Comment by gatoona** [comment]
@jmilden-git develop might not be merged to your feature branch. If you're having issues on git, please merge via the GitHub UI. Since you have disabled editing for this PR, I am unable to do so.

**Review by gatoona — APPROVED** [review]

**Comment by gatoona** [comment]
@lgbridges ready to be merged. Need add .acquia-cli.yml to .gitignore in a future PR.

**Pull request merged**
