### PR TITLE
WCOR-0: Hotfix/webform libraries

### PR DESCRIPTION
**Pull request by gatoona**
### ODE 70

**Fix Case for #88** 

Fix Drupal status report warnings and mirror configurations from forms server.

**Implementation Details**

- Install webform libraries locally instead of relying on external CDN.
- Enable jquery_ui_datepicker.

**Test Plan**

- Check to see Webform library errors have been hidden in status report (/admin/reports/status).
- Successfully add a date picker field in a test form and collect its value when submitted.

### CODE REVIEW

**Comment by lgbridges** [comment]
@gatoona Curious about the local hosting. Have there been issues with CDN hosting of libs in on-prem Forms Server?

We can obviously switch between CDN/local at any time, but I'm wondering if at least components/libraries that are author facing only (not public facing) should remain CDN hosted. CKeditor, primarily.

Don't want to split hairs for the sake of it, just have a sense that CDN hosting of components may reduce bottlenecking if we can keep that in play where possible.

**Comment by gatoona** [comment]
> @gatoona Curious about the local hosting. Have there been issues with CDN hosting of libs in on-prem Forms Server?
> 
> We can obviously switch between CDN/local at any time, but I'm wondering if at least components/libraries that are author facing only (not public facing) should remain CDN hosted. CKeditor, primarily.
> 
> Don't want to split hairs for the sake of it, just have a sense that CDN hosting of components may reduce bottlenecking if we can keep that in play where possible.

@lgbridges it is recommended by the module and Drupal to install them locally: https://www.drupal.org/docs/contributed-modules/webform/webform-libraries 

It even shows up as a warning in our Drupal and add this ass the reason: Relying on a CDN for external libraries can cause unexpected issues with Ajax and BigPipe support. For more information see: Issue [#1988968](https://www.drupal.org/project/drupal/issues/1988968)

The CKEditor libraries being installed from composer.libraries.json is only being used for webform fields.

**Comment by gatoona** [comment]
@lgbridges also forgot to answer your question. The forms server is also hosting the libraries locally.

**Comment by jmilden-git** [comment]
Why was this work a Hotfix vs regular WCOR story? The webform module story passed CR and QA.  We should reserve the hotfix label for things that are broken.  Also we need to discuss the best option for Captchas on forms.

**Comment by gatoona** [comment]
> Why was this work a Hotfix vs regular WCOR story? The webform module story passed CR and QA.

@jmilden-git this is a hotfix because we are not able to import current configurations from forms server into this environment without the enablement of certain libraries and modules like captcha and date_picker. The configuration setup for this webform environment should resemble the setup for the forms server as close as possible. These are items that were missed during QA and is being implemented now.

> We should reserve the hotfix label for things that are broken. 

No we should not. We already have a label for resolving things that are broken. Please refer to the README documentation:

- feature (actual functionality development)
- hotfix (short-fuse correction of an issue)
- bugfix (fix a bug)
- spike (experimentation in support of research)

> Also we need to discuss the best option for Captchas on forms.

Team was utilizing reCaptcha v2 prior in the forms server before a F5 network issue broke the functionality. We will probably just reimplement that back on while also utilizing honeypot to detect bots that can bypass the captcha.

**Comment by lgbridges** [comment]
For this sprint, let's move forward with this hotfix PR. We will discuss the future scope of hotfixes in detail in Friday's retro.

Webforms are among the most vulnerable pieces of any web application. The hotfix is being done to ensure the security reinforcement of CAPTCHA and Honeypot are imposed right away, and also to ensure configuration parity with our Drupal Forms Server in production now, before entering any webform submission data.

The changes are substantial enough that we should run QA for this when it's ready.

**Comment by lgbridges** [comment]
@gatoona -- Will you be providing a test plan for QA?

**Comment by gatoona** [comment]
> @gatoona -- Will you be providing a test plan for QA?

@lgbridges see 1st comment.

**Review by lgbridges — APPROVED** [review]
Test plan passes.

Noting that reCAPTCHA will be a separate story.

**Pull request merged**
