### PR TITLE
WCOR-1080: Add Webform module.

### PR DESCRIPTION
**Pull request by jmilden-git**
The Webform module has been added.  It has many more features and examples than it used to have.  Don't get scared by the number of files it added.  We can always turn off parts later.
**ODE 59**

Use case
As a admin, I can create and use Drupal webforms.

Implementation details
Install and enable webform module. https://www.drupal.org/project/webform
Add most common elements and example webforms.  Enable access control, dedicated node output and import / export options.

Test plan
You should be able to create a webform, successfully submit and see the output as expected.  Any required fields should trigger an error if left blank.

Acceptance criteria
Test plan passes.

### CODE REVIEW

**Comment by gatoona** [comment]
Taking QA and CR. @jmilden-git please merge the latest changes made to DEV.

**Comment by jmilden-git** [comment]
@gatoona I'm trying to merge the latest in the IDE, but not getting it to work.  Need some help with the commands.  I want to avoid using the GitHub update branch button.

**Comment by lgbridges** [comment]
> @gatoona I'm trying to merge the latest in the IDE, but not getting it to work. Need some help with the commands. I want to avoid using the GitHub update branch button.

I would actually try the Update Branch button first. If Pipelines fails after _that_, I think doing a ``` git pull ``` should get things moving. It may require you to resolve conflicts (if any) via the terminal, which we can huddle about if the process is unclear.

@gatoona Any other thoughts?

**Comment by lgbridges** [comment]
> > @gatoona I'm trying to merge the latest in the IDE, but not getting it to work. Need some help with the commands. I want to avoid using the GitHub update branch button.
> 
> @joshuami I would actually try the Update Branch button first. If Pipelines fails after _that_, I think doing a `git pull` should get things moving. It may require you to resolve conflicts (if any) via the terminal, which we can huddle about if the process is unclear.
> 
> @gatoona Any other thoughts?

**Comment by jmilden-git** [comment]
I tried all this and it did "fast forward" but there is nothing to push, so not sure what I'm missing.
git checkout develop
git merge feature/number
git push -u origin feature/number

**Comment by lgbridges** [comment]
> 
> 
> I tried all this and it did "fast forward" but there is nothing to push, so not sure what I'm missing.
> git checkout develop
> git merge feature/number
> git push -u origin feature/number

Don't quote me on it, as I'm still getting comfy with gitflow, but I wonder if you just needed to insert ``` git pull ``` after you checkout develop:

git checkout develop
git pull
git merge feature/number
git push -u origin feature/number

**Comment by gatoona** [comment]
@lgbridges @jmilden-git  unless you are comfortable merging and handling merge conflicts through the terminal, I would suggest just using the 'update branch' button and pulling in the changes into your feature branch. 

You should not be checking out develop and merging your feature branches into it through your terminal. That action should only be done in GitHub by @lgbridges.

**Comment by lgbridges** [comment]
> 
> 
> @lgbridges @jmilden-git unless you are comfortable merging and handling merge conflicts through the terminal, I would suggest just using the 'update branch' button and pulling in the changes into your feature branch.
> 
> You should not be checking out develop and merging your feature branches into it through your terminal. That action should only be done in GitHub by @lgbridges.

I agree, I think this is the best route. (Disregard my git instructions, I haven't mastered command-line git yet.)

The main reason Update Branch button didn't work previously, I think, was actually due to config/DB sync issues due to a bug, but I don't think that should be happening too often.

**Comment by gatoona** [comment]
@lgbridges there is another security requirement failing pipelines.
@jmilden-git please update phpmailer/phpmailer and push.

**Comment by jmilden-git** [comment]
This is exactly why using the button in GitHub never works.  I don't know what phpmailer is or how to update that.

**Comment by gatoona** [comment]
> This is exactly why using the button in GitHub never works.

This has nothing to do with merging through GitHub UI.

**Comment by lgbridges** [comment]
> This is exactly why using the button in GitHub never works. I don't know what phpmailer is or how to update that.

I would do ``` composer update phpmailer/phpmailer ```, then git add, git commit, and git push.

Unfortunately, Pipelines is pretty picky about what kind of build it will accept. I haven't addressed it in docs, but we will all have to review the Pipelines log output and try to get a handle on what's needed to move it forward.

Let us know if this approach works for you.

**Comment by gatoona** [comment]
@lgbridges I am applying the update to #81 since it's an earlier PR.

**Comment by gatoona** [comment]
@lgbridges Update added to #81 and ready for merge to dev.

**Comment by lgbridges** [comment]
> 
> 
> @lgbridges Update added to #81 and ready for merge to dev.

@jmilden-git I've merged PR81 which included the phpmailer update. Re-ran Pipelines, but still fails. My best guess is you'll still need to checkout develop, ``` git pull ```, checkout feature branch, ``` composer install ``` to get your composer.json / composer.lock files updated with that updated phpmailer dependency.  Then git add, git commit, and git push in order to get Pipelines to run.

Perhaps someone else can confirm this.

**Comment by gatoona** [comment]
@lgbridges this PR is still one commit behind develop. @jmilden-git hasn't merged in commits from #81 yet so running pipelines for this would still fail. Need to resolve conflicts before merging the latest dev commit.

**Comment by jmilden-git** [comment]
@lgbridges I ran those commands and composer didn't find anything new.  Maybe I should just dump this PR and start over, seems like a quicker path to resolution.

**Comment by jmilden-git** [comment]
@gatoona Do you know which hash is the correct one?
<<<<<<< feature/WCOR-1080
    "content-hash": "770b394a4432a3730cae873f748cc7d1",
=======
    "content-hash": "9c701be2b97bed0883ec1d84f6a41f29",
>>>>>>> develop

**Comment by gatoona** [comment]
> @gatoona Do you know which hash is the correct one?

@jmilden-git in most cases, you'll want to go with approving the latest incoming changes. So for this one, you'll want to approve the changes coming in from develop (9c70...).

**Comment by gatoona** [comment]
@jmilden-git run the following commands now in your IDE:

- `git checkout feature/WCOR-1080`
- `git pull origin feature/WCOR-1080 --force`
- `composer update --lock`
- `git add .`
- `git commit -m "WCOR-1080: Update composer.lock to reflect composer.json changes."`
- `git push -u origin feature/WCOR-1080`

**Comment by jmilden-git** [comment]
@gatoona Thanks for the tips, looks like it worked this time.

**Comment by gatoona** [comment]
@jmilden-git looks like you ran a blank `composer update` that updated all the dependencies in your commit 
ae81611. While this has passed, the QA is now a bigger task since now we have to test and see if all the dependencies like drush that got updated is without issue. I would revert back to commit caa88b6 and run the `composer update --lock` correctly.

Let me know if you want me to just go ahead and do that.

**Comment by jmilden-git** [comment]
@gatoona This is the result, I need some help with this step
git revert caa88b6915fa8d1208c591256020fc0fba234f27
error: commit caa88b6915fa8d1208c591256020fc0fba234f27 is a merge but no -m option was given.
fatal: revert failed

**Comment by gatoona** [comment]
@jmilden-git run the following commands:

- `git reset caa88b6915fa8d1208c591256020fc0fba234f27 --hard`
- `composer update --lock`
- `git add .`
- `git commit -m "WCOR-1080: Update composer.lock to reflect composer.json changes."`
- `git push -u origin feature/WCOR-1080 --force`

**Comment by jmilden-git** [comment]
@gatoona  It passed, is that good enough?

**Review by gatoona — APPROVED** [review]
QA and CR passes.

**Pull request merged**
