### PR TITLE
WCOR-1115: Create a standard contact information view-page for groups

### PR DESCRIPTION
**Pull request by lgbridges**
### ODE 121

**Use case**

As a member of the content migration team, I don't need to create individual pages for each web group's "Contact Us" or equivalent -- the view-page available at /contact/[group-name] will pull all relevant details from associated Service Location and Building content types, ensuring the information will never become stale as long as the associated Service Location and Building details are kept up-to-date.

As a site visitor, I can always enter the URL /contact/[group-name] to see the group's contact details, displayed in a consistent format.

**Implementation details**

Add Primary Service Location field to Group, and create a view for that field autocomplete that will display a list of service locations with their parent buildings. (Update Spec Tool accordingly.) Ensure a Service Location exists and is associated with a Group.

Create a page under the Groups view that is accessible via path /[group-name]/contact displaying all key fields from Group and Primary Service Location. The group may have multiple service locations given all subordinate groups, but the focus should be on the Primary Service Location designated on the Group item (however, a right sidebar set of links should display subordinate group contact links to jump to their contact view-page).

The page should pull the following fields from Service Location: telephone number, email, address of primary service location, office hours.

**Test plan**

- [x] Create a new Service Location (example: Suite B-14) and assign a parent Building (example: Public Services Building). Mark published and save.
- [x] Find a group (example: Information Technology Services) and assign the newly created Service Location as Primary Service Location for the group. Before leaving the edit form, adjust the group path to remove any nesting and shorten the path (e.g. _its_) and make note of that path for the next step.
- [x] As a site visitor (anon), I can enter any group contact view-page URL as /contact/[group-path] to see contact details (e.g. /contact/its). 
- [x] As anon, on the group contact view-page I can see a list of subordinate group contact links in the right sidebar, and can click on one to see its associated contact view-page
- [x] As anon, I can click the "More" link at the bottom of the right sidebar list to see a page (/contact/[group-path]/associated) showing all Associated (Subordinate) Groups for the current Group.

### CODE REVIEW

**Comment by jmilden-git** [comment]
The Test Plan was interesting.  I don't think a site visitor will change the URL manually to see the contact information of a group.  However, for demonstration purposes we see how the contact information is now linked to group.  Also as noted in the Demo, this functionality will continue to evolve as we determine how Groups are defined and associated to each other.

**Review by jmilden-git — APPROVED** [review]
QA Test passed.

**Comment by gatoona** [comment]
@lgbridges only minor correction needed is within the view, you get a ',' at the bottom. (Ex. /contact/lut)

Would just add a simple fix that shows nothing if results are empty in the field properties.

**Comment by gatoona** [comment]
@lgbridges still seeing a standalone ',' at the bottom of the view. 
Might want to use a rewrite for '(field_primary_service_location: Content) Content: Title [hidden]' to be ', {{ title_1 }} ' instead of having a custom text (Global: Custom text (Service location display) [hidden]) to rewrite that data.

**Comment by jmilden-git** [comment]
image
Also the new theme seems to have eliminated the right sidebar.  Not loving the new theme.
@lgbridges

**Comment by lgbridges** [comment]
> 
> 
> @lgbridges still seeing a standalone ',' at the bottom of the view.
> Might want to use a rewrite for '(field_primary_service_location: Content) Content: Title [hidden]' to be ', {{ title_1 }} ' instead of having a custom text (Global: Custom text (Service location display) [hidden]) to rewrite that data.

Fixed.

**Comment by lgbridges** [comment]
Clarified test plan.

**Comment by gatoona** [comment]
@lgbridges nested group paths don't seem to work with /contact (Ex. /supportservices/information-technology-services)
Would recommend using query parameters to grab the proper values in lieu of depending on the URL.

Examples:
- /contact?group=supportservices/information-technology-services
- /contact?group=supportservices

**Review by jmilden-git — CHANGES_REQUESTED** [review]
The final QA test is not passing.  No links in right sidebar were found.  Unrelated the breadcrumb is missing for any level past Home.

**Comment by lgbridges** [comment]
> 
> 
> @lgbridges nested group paths don't seem to work with /contact (Ex. /contact/supportservices/information-technology-services)
> Would recommend using query parameters to grab the proper values in lieu of depending on the URL.
> 
> Examples:
> 
>     * /contact?group=supportservices/information-technology-services
> 
>     * /contact?group=supportservices

Gotta be honest, this is a pretty terrible looking URL format. With the upcoming story WCOR-1159, we're going to implement flattened path structure for groups, so I'm not worried about implementing nesting for this story.

**Comment by lgbridges** [comment]
> 
> 
> The final QA test is not passing. No links in right sidebar were found. Unrelated the breadcrumb is missing for any level past Home.

@jmilden-git Which page is not displaying right sidebar links? The group being viewed in the contact view-page must have child groups. Please add a screenshot if you like.

Breadcrumbs will need to be addressed in a separate story. This sprint's WCOR-1159 will include menu breadcrumb configuration and I will add a note to fix the display of breadcrumbs for contact view-pages.

**Review by gatoona — APPROVED** [review]
Passes CR. Some minor issues with nested paths not working with /contact/? but can address in a future item.

**Pull request merged**
