### PR TITLE
WCOR-1104: Add translation selection menu block.

### PR DESCRIPTION
**Pull request by mitziklambert**
### ODE 127

**Use/Fix Case** 

As a user that speaks a language other than English, when I view a piece of content, I can see a menu titled "translation" in the language of the page I'm viewing with titles for each language that has been translated.

**Implementation Details**

Created a 'Translation' block view to display translated titles of content if/when they exist. The content shows up when the node ID is passed from the URL. Placed the block into the Sidebar block so it shows up on the right side of a 'Page' or a 'News" content type. 

**Dependencies**

Dependent on translated content for same node ID.

**Test Plan**

- [x] Navigate to the LUT 'Permits' page or find it in the Content list. 
- [x] Create a Spanish translation with the title 'Permisos'.
- [x] The Translation block should appear on the right side of the page with the 'Permisos' title in Spanish.

### CODE REVIEW

**Comment by jmilden-git** [comment]
I'll take QA.

**Comment by jmilden-git** [comment]
@mitziklambert  I'm not finding the translation block on the Permits page.  No Spanish either.  Let me know if you want to look together. 
image

**Comment by lgbridges** [comment]
> 
> 
> @mitziklambert I'm not finding the translation block on the Permits page. No Spanish either. Let me know if you want to look together.
> image

The translation itself didn't carry over to the ODE since it's content. Updated the test plan.

**Review by lgbridges — DISMISSED** [review]

**Comment by lgbridges** [comment]
Will pull this into IDE and correct issues shortly.

**Review by lgbridges — APPROVED** [review]

**Pull request merged**
