### PR TITLE
WCOR-0020530: Add contact content type.

### PR DESCRIPTION
**Pull request by jmilden-git**

### CODE REVIEW

**Comment by gatoona** [comment]
Taking QA and CR.

**Comment by jmilden-git** [comment]
@gatoona  Do you need any help with QA?

**Review by gatoona — CHANGES_REQUESTED** [review]
Title's label should replace contact name.
Remove translate from contact name field and remove option to include multiple contact name values (should only be one contact name per node.)

**Comment by jmilden-git** [comment]
@gatoona The spec sheet has translate for field Contact Name.  I'm not following the comment about Title field.

**Comment by gatoona** [comment]
> @gatoona The spec sheet has translate for field Contact Name. I'm not following the comment about Title field.

Positive the spec sheet is incorrect as names shouldn't be translated. @lgbridges can you recall why the translation was checked for contact name?

@jmilden-git the default title field should be used for contact name as it's listed as a 'Entity label,' in the spec sheet. Just change the label for it and remove existing contact name field.

**Comment by lgbridges** [comment]
Changed the spec sheet to mark names as not translated.

**Comment by jmilden-git** [comment]
@gatoona Changes have been made.

**Comment by gatoona** [comment]
@jmilden-git not seeing any new commits with changes.

**Comment by jmilden-git** [comment]
@gatoona It worked this time.

**Review by gatoona — APPROVED** [review]

**Review by lgbridges — APPROVED** [review]
QA previously passed, no functional changes since. Code review good. Ready to merge.

**Pull request merged**
