### PR TITLE
WCOR-1118: Configure SMTP to allow for outbound emails.

### PR DESCRIPTION
**Pull request by gatoona**
### ODE 90

**Use/Fix Case** 

As a user, I would like to receive emails (Ex. webform submission confirmations, moderation reviews, etc) from the site.

**Implementation Details**

- Enable drupal/smtp
- Configure SMTP settings
- Store credentials in secrets file.

**Dependencies**

- [drupal/smtp](https://www.drupal.org/project/smtp)
- AWS SES (temporary)

**Test Plan**

- [ ] At the bottom of /admin/config/system/smtp, send a test email to yourself and confirm its arrival.

### CODE REVIEW

**Comment by sharstine** [comment]
I'll take the QA on this.

**Comment by sharstine** [comment]
@gatoona - When I attempt to send a test email via /admin/config/system/smtp, the following errors are logged in "Recent log messages" and I don't receive the emails. I tested two email addresses and got the same error and no email both times: scotthar.washco@gmail.com and scott_harstine@co.washington.or.us.

`Error sending e-mail from noreply@washcotech.net to scotthar.washco@gmail.com: The following From address failed: noreply@washcotech.net : MAIL FROM command failed,Authentication required ,530,SMTP server error: MAIL FROM command failed Detail: Authentication required SMTP code: 530SMTP server error: MAIL FROM command failed Detail: Authentication required SMTP code: 530`

`Error sending email (from noreply@washcotech.net to scotthar.washco@gmail.com with reply-to not set).`

**Comment by gatoona** [comment]
@sharstine try it now. Credentials have been added to that environment.

**Comment by sharstine** [comment]
@gatoona @lgbridges 

Sent test emails to scotthar.washco@gmail.com and scott_harstine@co.washington.or.us via /admin/config/system/smtp. I received both emails. No errors were logged in Drupal.

Created a web form with an email template. Submitted form and received email submissions at scotthar.washco@gmail.com and scott_harstine@co.washington.or.us. No errors were logged in Drupal.

QA passes.

**Review by lgbridges — APPROVED** [review]

**Pull request merged**
