### PR TITLE
WCOR-1218: Streamline contacts and allow for grouping and separate views.

### PR DESCRIPTION
**Pull request by jlwcor**
### ODE 216

**Use/Fix Case** 

As an author, I would like to be able to create a list of contacts and have them automatically displayed as a table/card in a page. When I update that contact information, it will changed on all pages that reference that contact.

**Implementation Details**

- Develop new node page twig based on page type selected.
- Disable EVA for phone number rendering in pages. Replace with twig conditions.
- Create contact field for page content types.
- Create reference view for selecting contacts by name, phone, or email.

**Dependencies**

- drupal/radix

**Test Plan**

- [x] I can reference a list of contacts on a page and with 'contacts' selected as page type, it will automatically render the page as a contact data list. 
- [x] Contact rows turn into individual cards on mobile view.
- [x] Formatting of email and phone (including extension and notes) looks okay.

### CODE REVIEW

**Comment by jmilden-git** [comment]
Not quite sure how to execute the test plan.  A few more instructions would help clarify.

**Comment by jlwcor** [comment]
> Not quite sure how to execute the test plan. A few more instructions would help clarify.

@jmilden-git broken down step-by-step instructions on how to complete task 1:

1.  Create and publish several test contacts (2-3).
2. Create a new page to serve as the contact list page (Ex. Park Maintenance Contacts)
3. Fill out the required fields. Most important is select, 'Contacts' for page type.
4. At the bottom of the page, add all the contacts created in step 1 to the contacts fields.
5. Save and view page.

**Comment by jmilden-git** [comment]
@jlwcor I like the overall way this works, nice job.  However a minor formatting issue on the last step.  My test contacts have phone extentions, but they are not appearing on the list page.  
https://wcorode216.prod.acquia-sites.com/support-services/its-contacts

**Comment by jlwcor** [comment]
@jmilden-git I am seeing extensions on my end. Which contact is not showing it?

**Comment by jmilden-git** [comment]
@jlwcor QA passes.  The caching will be an issue for lots of content in the future.  We'll just have to have some training reminders about clearing cache for certain things.

**Review by lgbridges — APPROVED** [review]

**Pull request merged**
